Makes Description Optional on Personal Schedule
ucsb-cs156-f24/proj-courses-f24-03 pull request #13
Opened 2024-11-16 11:55 UTC by bsaiju

Closes #8 

# Before commit:
## When creating personal schedule without description:
<img width="1360" alt="Screenshot 2024-11-16 at 3 43 06 AM" src="https://github.com/user-attachments/assets/86ec9f42-ee0c-4923-a84a-20a89ef90111">

## When editing personal schedule to clear out description:
<img width="1373" alt="Screenshot 2024-11-16 at 3 43 49 AM" src="https://github.com/user-attachments/assets/ca57a93e-031f-43c4-8412-bc938748a1ba">

# After commit:
## When creating personal schedule without description:
<img width="1285" alt="Screenshot 2024-11-16 at 3 48 51 AM" src="https://github.com/user-attachments/assets/4a701a27-8d75-4baf-91f0-69c0bf4bc3c1">
*Clicks Create Button*
<img width="1306" alt="Screenshot 2024-11-16 at 3 49 09 AM" src="https://github.com/user-attachments/assets/c17f1a5a-1eae-427e-b34b-18213ff36bca">

## When editing personal schedule to clear out description:
<img width="1257" alt="Screenshot 2024-11-16 at 3 50 09 AM" src="https://github.com/user-attachments/assets/085039d0-45f6-4385-b416-e91887835dc1">
*Clicks Edit button*
<img width="1305" alt="Screenshot 2024-11-16 at 3 50 28 AM" src="https://github.com/user-attachments/assets/35d9058e-2fae-4f91-92bb-9b2770d828d7">
*Clicks Update Button*
<img width="1268" alt="Screenshot 2024-11-16 at 3 50 53 AM" src="https://github.com/user-attachments/assets/132b6f5d-d8c6-455f-b6ba-b28549d55c12">

2024-11-20 17:55 UTC, pconrad requested changes
I have a question about whether adding `stryker` to package.json is necessary.

Further, if it is, is probably doesn't go in `dependencies` but in `dev-dependencies`, but still, I would have expected that `"@stryker-mutator/jest-runner": "^8.5.0",` in `dev-dependencies` would be enough.

2024-11-21 01:52 UTC, bsaiju commented on frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
> +    // expect(screen.getByText(/Description is required./)).toBeInTheDocument();
this is fixed in the previous commit.

2024-11-21 01:54 UTC, bsaiju commented
> I have a question about whether adding `stryker` to package.json is necessary.
> 
> Further, if it is, is probably doesn't go in `dependencies` but in `dev-dependencies`, but still, I would have expected that `"@stryker-mutator/jest-runner": "^8.5.0",` in `dev-dependencies` would be enough.

I did not specifically edit it. I believe it was added when I ran npm install or mvn install or something of the like. Should I delete that line?

2024-11-22 00:10 UTC, pconrad requested changes
Please restore package-lock.json since package.json is not being changed.

https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html

2024-11-22 01:51 UTC, ChristopherChau submitted a review, later dismissed
LGTM

2024-11-23 21:33 UTC, pconrad requested changes
Please remove changes to package-lock.json from this PR.

Please see: https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html

2024-11-23 21:38 UTC, pconrad commented
When I said: remove the changes to package-lock.json, I meant it.

<img width="768" alt="image" src="https://github.com/user-attachments/assets/674085ac-b022-48e5-b4bb-362c06702550">

This still shows that package-lock.json was updated.

You need to follow the steps at this page: https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html

When you are done, the ONLY changes to this PR should be in two files:
* frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
* frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js

If you can't figure out how to do that in this branch, then close this PR, make a new branch off of main, and reapply the simple 1-2 lines changes in a new PR.  I said that I would not merge this one with change to package-lock.json, and I still won't.

If you want the points, then address the changes in the code review.  Don't just "remove the label".  That wastes everyone's time.

2024-11-24 01:06 UTC, closed without merging