Fixes bug that allowed schedules in the same quarter to have the same name
ucsb-cs156-f24/proj-courses-f24-03 pull request #43
Opened 2024-11-25 08:41 UTC by bsaiju

Closes #9 

# Before Fix

https://github.com/user-attachments/assets/6c198499-1204-4dba-9cdc-a0ac44df42c7

# After Fix

https://github.com/user-attachments/assets/971127e6-4347-4ac1-b7a3-0c500c088eed

2024-11-25 09:52 UTC, pballani approved these changes
LGTM

2024-11-25 21:08 UTC, pconrad requested changes
This implementation contains a bug.  See the comments on the PR.

2024-11-25 21:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
> +
There's a bug in this logic.  See the comment on the PR.

2024-11-28 20:18 UTC, pconrad commented
Closed, due to no response from team on Wednesday 11/17/2024:

<img width="919" alt="image" src="https://github.com/user-attachments/assets/6da6de74-738f-42e3-b27e-ca18bc39c041">

2024-11-28 20:18 UTC, closed without merging